/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package casestudentmanagement.view;

import Control.IDExist;
import casestudentmanagement.model.Student;
import java.awt.Color;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import java.awt.event.KeyEvent;

/**
 *
 * @author Hieu
 */
public class Add extends javax.swing.JDialog {
    Main main;
    /**
     * Creates new form Add
     */
    public Add(java.awt.Dialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
        main = (Main) parent;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbAddForm = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lbEnterInfor = new javax.swing.JLabel();
        lbID = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        lbLastName = new javax.swing.JLabel();
        txtLastName = new javax.swing.JTextField();
        lbSurName = new javax.swing.JLabel();
        txtSurName = new javax.swing.JTextField();
        lbBD = new javax.swing.JLabel();
        txtBD = new javax.swing.JTextField();
        lbEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lbAddress = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        btSave = new javax.swing.JButton();
        btCancel = new javax.swing.JButton();
        lbGrade = new javax.swing.JLabel();
        txtGrade = new javax.swing.JTextField();
        btClear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("ADD");
        setBackground(new java.awt.Color(204, 204, 204));

        jPanel1.setBackground(new java.awt.Color(255, 255, 153));

        lbAddForm.setBackground(new java.awt.Color(255, 255, 153));
        lbAddForm.setFont(new java.awt.Font(".VnArialH", 1, 24)); // NOI18N
        lbAddForm.setForeground(new java.awt.Color(255, 0, 0));
        lbAddForm.setText("ADD FORM");
        lbAddForm.setToolTipText("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbAddForm)
                .addGap(154, 154, 154))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbAddForm)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(204, 255, 204));

        lbEnterInfor.setFont(new java.awt.Font(".VnArialH", 1, 14)); // NOI18N
        lbEnterInfor.setForeground(new java.awt.Color(255, 0, 0));
        lbEnterInfor.setText("Student's Information");

        lbID.setFont(new java.awt.Font(".VnArialH", 1, 14)); // NOI18N
        lbID.setText("ID:");

        txtID.setFont(new java.awt.Font(".VnArial", 0, 12)); // NOI18N
        txtID.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtIDMouseClicked(evt);
            }
        });

        lbLastName.setFont(new java.awt.Font(".VnArialH", 1, 14)); // NOI18N
        lbLastName.setText("LASTName:");

        txtLastName.setFont(new java.awt.Font(".VnArial", 0, 12)); // NOI18N
        txtLastName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtLastNameMouseClicked(evt);
            }
        });

        lbSurName.setFont(new java.awt.Font(".VnArialH", 1, 14)); // NOI18N
        lbSurName.setText("SURName:");

        txtSurName.setFont(new java.awt.Font(".VnArial", 0, 12)); // NOI18N
        txtSurName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtSurNameMouseClicked(evt);
            }
        });

        lbBD.setFont(new java.awt.Font(".VnArialH", 1, 14)); // NOI18N
        lbBD.setText("Birth Day:");

        txtBD.setFont(new java.awt.Font(".VnArial", 0, 12)); // NOI18N
        txtBD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtBDMouseClicked(evt);
            }
        });

        lbEmail.setFont(new java.awt.Font(".VnArialH", 1, 14)); // NOI18N
        lbEmail.setText("Email:");

        txtEmail.setFont(new java.awt.Font(".VnArial", 0, 12)); // NOI18N
        txtEmail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtEmailMouseClicked(evt);
            }
        });

        lbAddress.setFont(new java.awt.Font(".VnArialH", 1, 14)); // NOI18N
        lbAddress.setText("Address:");

        txtAddress.setFont(new java.awt.Font(".VnArial", 0, 12)); // NOI18N
        txtAddress.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtAddressMouseClicked(evt);
            }
        });

        btSave.setFont(new java.awt.Font(".VnArialH", 1, 12)); // NOI18N
        btSave.setMnemonic(KeyEvent.VK_S);
        btSave.setText("SAVE");
        btSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSaveActionPerformed(evt);
            }
        });

        btCancel.setFont(new java.awt.Font(".VnArialH", 1, 12)); // NOI18N
        btCancel.setMnemonic(KeyEvent.VK_C);
        btCancel.setText("CANCEL");
        btCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelActionPerformed(evt);
            }
        });

        lbGrade.setFont(new java.awt.Font(".VnArialH", 1, 14)); // NOI18N
        lbGrade.setText("Grade:");

        txtGrade.setFont(new java.awt.Font(".VnArial", 0, 12)); // NOI18N
        txtGrade.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtGradeMouseClicked(evt);
            }
        });

        btClear.setFont(new java.awt.Font(".VnArialH", 1, 12)); // NOI18N
        btClear.setMnemonic(KeyEvent.VK_E);
        btClear.setText("CLEAR");
        btClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(lbEnterInfor)
                                .addGap(114, 114, 114))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(btClear)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btSave)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btCancel)
                                .addGap(40, 40, 40))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lbGrade, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbAddress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbBD, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbSurName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbID, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbLastName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtID, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE)
                                    .addComponent(txtLastName))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtSurName)
                            .addComponent(txtBD)
                            .addComponent(txtEmail)
                            .addComponent(txtAddress)
                            .addComponent(txtGrade))
                        .addGap(17, 17, 17))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbEnterInfor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbID)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbLastName)
                    .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbSurName)
                    .addComponent(txtSurName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbBD)
                    .addComponent(txtBD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbEmail)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbAddress)
                    .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbGrade)
                    .addComponent(txtGrade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSave)
                    .addComponent(btCancel)
                    .addComponent(btClear)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtLastNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtLastNameMouseClicked
        lbLastName.setForeground(Color.black);
// TODO add your handling code here:
    }//GEN-LAST:event_txtLastNameMouseClicked

    private void txtSurNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSurNameMouseClicked
        lbSurName.setForeground(Color.black);
    }//GEN-LAST:event_txtSurNameMouseClicked

    private void txtBDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBDMouseClicked
        lbBD.setForeground(Color.black);
    }//GEN-LAST:event_txtBDMouseClicked

    private void txtEmailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtEmailMouseClicked
        lbEmail.setForeground(Color.black);
    }//GEN-LAST:event_txtEmailMouseClicked

    private void txtAddressMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtAddressMouseClicked
        lbAddress.setForeground(Color.black);
    }//GEN-LAST:event_txtAddressMouseClicked

    private void txtGradeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtGradeMouseClicked
        lbGrade.setForeground(Color.black);
    }//GEN-LAST:event_txtGradeMouseClicked

    private void btSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSaveActionPerformed
        String ID = txtID.getText();
        if (IDExist.isIDExist(main.studentList, ID)) {
            lbID.setForeground(Color.red);            
            JOptionPane.showMessageDialog(rootPane, "This ID was existed");
            return;
        }
        String lastName = txtLastName.getText();
        String surName = txtSurName.getText();
        String address = txtAddress.getText();
        String email = txtEmail.getText();
        String BDString = txtBD.getText();
        Date birthDay = null;
        String gradeString = txtGrade.getText();
        double grade = 0d;
        try {
            birthDay = new SimpleDateFormat("dd/MM/yyyy").parse(BDString);
        } catch (ParseException ex) {
            lbBD.setForeground(Color.red);            
            JOptionPane.showMessageDialog(rootPane, "This format date is wrong");
//            ex.printStackTrace();
            return;
        }
        try {
            grade = Double.parseDouble(gradeString);
        } catch (Exception ex) {
            lbGrade.setForeground(Color.red);
            JOptionPane.showMessageDialog(rootPane, "Grade must be a a number");
            return;
//            ex.printStackTrace();
        }
        
        if (ID.equals("") || lastName.equals("") || surName.equals("") || address.equals("") ||
                email.equals("") || BDString.equals("") || gradeString .equals("")) {
            if (ID.equals("")) {
                lbID.setForeground(Color.red);
            }
            if (lastName.equals("")) {
                lbLastName.setForeground(Color.red);
            }
            if (surName.equals("")) {
                lbSurName.setForeground(Color.red);
            }
            if (address.equals("")) {
                lbAddress.setForeground(Color.red);
            }
            if (email.equals("")) {
                lbEmail.setForeground(Color.red);
            }
            if (BDString.equals("")) {
                lbBD.setForeground(Color.red);
            }
            if (gradeString.equals("")) {
                lbGrade.setForeground(Color.red);
            }
            JOptionPane.showMessageDialog(rootPane, "Please complete form");
        } else {            
            Student student = new Student(ID, lastName, 
            surName, birthDay,email, address, grade);
            main.addStudent(student);
            JOptionPane.showMessageDialog(rootPane, "Sucessfully");
           
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btSaveActionPerformed

    private void btCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelActionPerformed
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_btCancelActionPerformed

    private void txtIDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtIDMouseClicked
        lbID.setForeground(Color.black);
// TODO add your handling code here:
    }//GEN-LAST:event_txtIDMouseClicked

    private void btClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btClearActionPerformed
        txtID.setText("");
        txtLastName.setText("");
        txtSurName.setText("");
        txtBD.setText("");
        txtEmail.setText("");
        txtAddress.setText("");
        txtGrade.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_btClearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Add dialog = new Add(new javax.swing.JDialog(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCancel;
    private javax.swing.JButton btClear;
    private javax.swing.JButton btSave;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbAddForm;
    private javax.swing.JLabel lbAddress;
    private javax.swing.JLabel lbBD;
    private javax.swing.JLabel lbEmail;
    private javax.swing.JLabel lbEnterInfor;
    private javax.swing.JLabel lbGrade;
    private javax.swing.JLabel lbID;
    private javax.swing.JLabel lbLastName;
    private javax.swing.JLabel lbSurName;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtBD;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtGrade;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtSurName;
    // End of variables declaration//GEN-END:variables
}
